###
POST http://localhost:5000/registros HTTP/1.1
Content-Type: application/json

{
    "titulo": "prueba 3",
    "valor": 522006,
    "estado": "0"
}

###
GET http://localhost:5000/registros HTTP/1.1

###
GET http://localhost:5000/registros/6828ab015dc8fbbe14e0ee1b HTTP/1.1